// Role-based permissions configuration

const ROLES = {
  ADMIN: 'ADMIN',
  HOST_EMPLOYEE: 'HOST_EMPLOYEE',
  PROCESS_ADMIN: 'PROCESS_ADMIN',
  SECURITY_GUARD: 'SECURITY_GUARD',
  SECURITY_MANAGER: 'SECURITY_MANAGER'
};

const PERMISSIONS = {
  // User Management
  CREATE_USER: 'CREATE_USER',
  READ_USER: 'READ_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  APPROVE_USER: 'APPROVE_USER',
  
  // Visitor Management
  CREATE_VISITOR: 'CREATE_VISITOR',
  READ_VISITOR: 'READ_VISITOR',
  UPDATE_VISITOR: 'UPDATE_VISITOR',
  DELETE_VISITOR: 'DELETE_VISITOR',
  BLOCK_VISITOR: 'BLOCK_VISITOR',
  BLACKLIST_VISITOR: 'BLACKLIST_VISITOR',
  
  // Visit Management
  CREATE_VISIT: 'CREATE_VISIT',
  READ_VISIT: 'READ_VISIT',
  UPDATE_VISIT: 'UPDATE_VISIT',
  DELETE_VISIT: 'DELETE_VISIT',
  APPROVE_VISIT: 'APPROVE_VISIT',
  CHECK_IN_VISITOR: 'CHECK_IN_VISITOR',
  CHECK_OUT_VISITOR: 'CHECK_OUT_VISITOR',
  CREATE_WALKIN: 'CREATE_WALKIN',
  
  // Reports
  VIEW_REPORTS: 'VIEW_REPORTS',
  EXPORT_REPORTS: 'EXPORT_REPORTS',
  
  // Admin
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_ACTIVITY_LOGS: 'VIEW_ACTIVITY_LOGS',
  MANAGE_ROLES: 'MANAGE_ROLES'
};

// Role-Permission mapping
const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS), // Admin has all permissions
  
  [ROLES.HOST_EMPLOYEE]: [
    PERMISSIONS.CREATE_VISITOR,
    PERMISSIONS.READ_VISITOR,
    PERMISSIONS.UPDATE_VISITOR,
    PERMISSIONS.CREATE_VISIT,
    PERMISSIONS.READ_VISIT,
    PERMISSIONS.UPDATE_VISIT,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  [ROLES.PROCESS_ADMIN]: [
    PERMISSIONS.READ_VISITOR,
    PERMISSIONS.UPDATE_VISITOR,
    PERMISSIONS.READ_VISIT,
    PERMISSIONS.UPDATE_VISIT,
    PERMISSIONS.APPROVE_VISIT,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  [ROLES.SECURITY_GUARD]: [
    PERMISSIONS.READ_VISITOR,
    PERMISSIONS.READ_VISIT,
    PERMISSIONS.CHECK_IN_VISITOR,
    PERMISSIONS.CHECK_OUT_VISITOR,
    PERMISSIONS.CREATE_WALKIN,
    PERMISSIONS.VIEW_DASHBOARD
  ],
  
  [ROLES.SECURITY_MANAGER]: [
    PERMISSIONS.CREATE_VISITOR,
    PERMISSIONS.READ_VISITOR,
    PERMISSIONS.UPDATE_VISITOR,
    PERMISSIONS.BLOCK_VISITOR,
    PERMISSIONS.CREATE_VISIT,
    PERMISSIONS.READ_VISIT,
    PERMISSIONS.UPDATE_VISIT,
    PERMISSIONS.APPROVE_VISIT,
    PERMISSIONS.CHECK_IN_VISITOR,
    PERMISSIONS.CHECK_OUT_VISITOR,
    PERMISSIONS.CREATE_WALKIN,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD
  ]
};

// Check if role has permission
const hasPermission = (role, permission) => {
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permission);
};

// Check if role has any of the permissions
const hasAnyPermission = (role, permissions) => {
  return permissions.some(permission => hasPermission(role, permission));
};

// Check if role has all of the permissions
const hasAllPermissions = (role, permissions) => {
  return permissions.every(permission => hasPermission(role, permission));
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions
};
